---
- hosts: all
  connection: local
  become: true

  vars:
    vagrant_version: "2.0.2"
    vagrant_arch: "x86_64"
  
    packer_version: "1.2.0"
    packer_arch: "amd64"

    terraform_version: "0.11.3"
    terraform_arch: "amd64"
    
    pip_install_packages:
      - name: awscli
        state: latest

    go_version: "1.10"
    go_os: linux
    go_arch: amd64

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'

    - name: Fix broken apt module for Ubuntu 1604
      apt:
        name: "{{ item }}"
        state: present
      with_items:
      - python-simplejson
      - aptitude
      - apt-transport-https
      when: ansible_os_family == 'Debian'

  tasks:
  - import_role:
      name: brentwg.linux-customization
      
  - import_role:
      name: brentwg.google-chrome
      
  - import_role:
      name: brentwg.multimedia
      
  - import_role:
      name: brentwg.vagrant
  
  - import_role:
      name: brentwg.packer 

  - import_role:
      name: brentwg.terraform

  - import_role:
      name: brentwg.visual-studio-code
      
  - import_role:
      name: brentwg.docker
  
  - import_role:
      name: brentwg.pip

  - import_role:
      name: brentwg.gcloud-sdk
      
  - import_role:
      name: brentwg.azure-cli

  - import_role:
      name: brentwg.golang
