---
- hosts: all
  connection: local
  become: true

  vars:
    vagrant_version: "2.0.2"
    vagrant_arch: "x86_64"
  
    packer_version: "1.2.0"
    packer_arch: "amd64"

    terraform_version: "0.11.3"
    terraform_arch: "amd64"
    
    pip_install_packages:
      - name: awscli
        state: latest

  tasks:
  - import_role:
      name: brentwg.linux-customization
      
  - import_role:
      name: brentwg.multimedia
      
  - import_role:
      name: brentwg.vagrant
  
  - import_role:
      name: brentwg.packer 

  - import_role:
      name: brentwg.terraform

  - import_role:
      name: brentwg.visual-studio-code
      
  - import_role:
      name: brentwg.docker
  
  - import_role:
      name: brentwg.pip
      
