---
- name: brentwg.linux-customization
- name: brentwg.google-chrome
- name: brentwg.multimedia
- name: brentwg.vagrant
- name: brentwg.packer
- name: brentwg.terraform
- name: brentwg.visual-studio-code
- name: brentwg.docker
- name: brentwg.pip
- name: brentwg.gcloud-sdk
- src: brentwg.azure-cli
  version: "1.0"
- src: brentwg.golang
  version: "1.0"
